# action.yml
name: 'Bump Version'
description: 'Bump the major, minor, or patch part of a semantic version string'
inputs:
  type:
    description: The part of the version to bump, must be one of major, minor, patch, or a release name (e.g. anvil)
    required: true
  command:
    description: One of 'awk' or 'cat'. The command used to extract the current version.
    required: true
  file:
    description: The name of the file containing the versions information.
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.type }}
    - ${{ inputs.command }}
    - ${{ inputs.file }}
