name: Perform a release
on:
  pull_request_target:
    types:
      - closed
    branches:
      - master
jobs:
  release:
    name: Bump the version number, tag, and release.
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
           persist-credentials: true
      - uses: ksuderman/github-action-bump-version@dev
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          file: VERSION
          parser: cat
          type: simple
      - uses: ksuderman/github-action-tag-release@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          file: VERSION
          parser: cat
