name: Perform a release
on:
  workflow_dispatch:
jobs:
  release:
    #if: github.event.pull_request.merged == true
    name: Tag and Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ksuderman/github-action-tag-release@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          file: VERSION
          parser: cat
