name: Bump Version
on:
  workflow_dispatch:
jobs:
  bump:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
           persist-credentials: false
      - uses: ksuderman/github-action-bump-version@dev
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          parser: cat
          file: VERSION
          type: simple